match "taste/white-full" => "taste#white_full"
match "taste/white-soft" => "taste#white_soft"

match "taste/white-full-fruity" => "taste#white_full_fruity"
match "taste/white-soft-fruity" => "taste#white_soft_fruity"
match "taste/white-full-not" => "taste#white_full_not"
match "taste/white-soft-not" => "taste#white_soft_not"

match "taste/white-full-fruity-dry" => "taste#white_full_fruity_dry"
match "taste/white-soft-fruity-dry" => "taste#white_soft_fruity_dry"
match "taste/white-full-not-dry" => "taste#white_full_not_dry"
match "taste/white-soft-not-dry" => "taste#white_soft_not_dry"
match "taste/white-full-fruity-not" => "taste#white_full_fruity_not"
match "taste/white-soft-fruity-not" => "taste#white_soft_fruity_not"
match "taste/white-full-not-not" => "taste#white_full_not_not"
match "taste/white-soft-not-not" => "taste#white_soft_not_not"

match "taste/white-full-fruity-dry-tannic" => "taste#white_full_fruity_dry_tannic"
match "taste/white-soft-fruity-dry-tannic" => "taste#white_soft_fruity_dry_tannic"
match "taste/white-full-not-dry-tannic" => "taste#white_full_not_dry_tannic"
match "taste/white-soft-not-dry-tannic" => "taste#white_soft_not_dry_tannic"
match "taste/white-full-fruity-not-tannic" => "taste#white_full_fruity_not_tannic"
match "taste/white-soft-fruity-not-tannic" => "taste#white_soft_fruity_not_tannic"
match "taste/white-full-not-not-tannic" => "taste#white_full_not_not_tannic"
match "taste/white-soft-not-not-tannic" => "taste#white_soft_not_not_tannic"
match "taste/white-full-fruity-dry-not" => "taste#white_full_fruity_dry_not"
match "taste/white-soft-fruity-dry-not" => "taste#white_soft_fruity_dry_not"
match "taste/white-full-not-dry-not" => "taste#white_full_not_dry_not"
match "taste/white-soft-not-dry-not" => "taste#white_soft_not_dry_not"
match "taste/white-full-fruity-not-not" => "taste#white_full_fruity_not_not"
match "taste/white-soft-fruity-not-not" => "taste#white_soft_fruity_not_not"
match "taste/white-full-not-not-not" => "taste#white_full_not_not_not"
match "taste/white-soft-not-not-not" => "taste#white_soft_not_not_not"
