--- 
- !ruby/object:Rubber::Configuration::InstanceItem 
  domain: gettipsi.com
  external_host: ec2-50-19-36-20.compute-1.amazonaws.com
  external_ip: 50.19.36.20
  image_id: ami-7000f019
  image_type: t1.micro
  instance_id: i-e7d2ae83
  internal_host: ip-10-111-53-130.ec2.internal
  internal_ip: 10.111.53.130
  name: production
  platform: linux
  roles: 
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: web
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: haproxy
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: app
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: passenger
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: apache
    options: {}

  - !ruby/object:Rubber::Configuration::RoleItem 
    name: db
    options: 
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem 
    name: mysql_master
    options: {}

  root_device_type: instance-store
  security_groups: 
  - tipsi_production_default
  - tipsi_production_web
  - tipsi_production_production
  - tipsi_production_haproxy
  - tipsi_production_app
  - tipsi_production_passenger
  - tipsi_production_apache
  - tipsi_production_db
  - tipsi_production_mysql_master
  zone: us-east-1c

- volumes: {}

  static_ips: {}

